## You can make your own storage class if you want or else it will use a default storage class.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: azizstorageclass
provisioner: kubernetes.io/aws-ebs
parameters: 
   type: gp2
reclaimPolicy: Retain